const EVENT_TYPES = {
  USER_CREATED: "USER_CREATED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
};

const RPC_TYPES = {
  TEST_RPC: "TEST_RPC",
  GET_USER_DETAILS: "GET_USER_DETAILS",
  GET_USER_RESUME: "GET_USER_RESUME",
  CHECK_USER_EXISTENCE: "CHECK_USER_EXISTENCE",
};

module.exports = {
  EVENT_TYPES,
  RPC_TYPES,
};
